include:
    - docker/docker-mysql.yml

services:
    sqlscript:
        image: jekkos/opensourcepos:sql-master
        command: /bin/sh -c 'exit 0'
    ospos:
        image: jekkos/opensourcepos:master
        restart: always
        depends_on:
            - mysql
        ports:
            - "5486:80"
        networks:
            - app_net
        volumes:
            - uploads:/app/public/uploads
            - logs:/app/writable/logs
        environment:
            - CI_ENVIRONMENT=development
            - FORCE_HTTPS=false
            - PHP_TIMEZONE=UTC
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql
            - encryption.key=hex2bin:473ee1a2e8804d2a216133bded846f0863a3b14f737d13eba5cd4f6efde363c5
